### ISSUE TITLE
docker imageのベースをubuntu20.04(focal)に更新したい

### ISSUE THREAD

**Issue by seigot** [seigot/tetris#21]
docker imageのベースをubuntu20.04(focal)に更新したい

patch 

```
diff --git a/docker/Dockerfile.latest b/docker/Dockerfile.latest
index eb14ef7..fb4be3c 100644
--- a/docker/Dockerfile.latest
+++ b/docker/Dockerfile.latest
@@ -1,4 +1,4 @@
-FROM dorowu/ubuntu-desktop-lxde-vnc:bionic
+FROM dorowu/ubuntu-desktop-lxde-vnc:focal
 LABEL maintainer="seigot<s.takada.3o3@gmail.com>"
 
 RUN apt-get update -q && \
@@ -36,7 +36,7 @@ RUN apt-get update ;\
     lsb-release \
     terminator \
     gnome-terminal \
-    emacs25;
+    emacs;
 
 # turtlebot3
 #RUN apt-get update ;\
diff --git a/docker/Dockerfile.pytorchv1.10 b/docker/Dockerfile.pytorchv1.10
index ecd42dc..08fba71 100644
--- a/docker/Dockerfile.pytorchv1.10
+++ b/docker/Dockerfile.pytorchv1.10
@@ -1,4 +1,4 @@
-FROM dorowu/ubuntu-desktop-lxde-vnc:bionic
+FROM dorowu/ubuntu-desktop-lxde-vnc:focal
 LABEL maintainer="seigot<s.takada.3o3@gmail.com>"
 
 RUN apt-get update -q && \
@@ -36,7 +36,7 @@ RUN apt-get update ;\
     lsb-release \
     terminator \
     gnome-terminal \
-    emacs25;
+    emacs;
 
 # turtlebot3
 #RUN apt-get update ;\
```

しかし起動時に以下のようなエラーが出る

```
$ sudo docker run -p 6080:80 --shm-size=512m seigott/tetris_docker
* enable custom user: ubuntu
useradd: user 'ubuntu' already exists
  set default password to "ubuntu"
cp: cannot stat '/root/.config': No such file or directory
2022-02-23 01:27:16,837 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-02-23 01:27:16,837 INFO Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
2022-02-23 01:27:16,840 INFO RPC interface 'supervisor' initialized
2022-02-23 01:27:16,840 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2022-02-23 01:27:16,840 INFO supervisord started with pid 18
2022-02-23 01:27:17,844 INFO spawned: 'nginx' with pid 20
2022-02-23 01:27:17,848 INFO spawned: 'web' with pid 21
2022-02-23 01:27:17,852 INFO spawned: 'xvfb' with pid 22
2022-02-23 01:27:17,854 INFO spawned: 'wm' with pid 23
2022-02-23 01:27:17,855 INFO spawned: 'lxpanel' with pid 24
2022-02-23 01:27:17,857 INFO spawned: 'pcmanfm' with pid 25
2022-02-23 01:27:17,858 INFO spawned: 'x11vnc' with pid 26
2022-02-23 01:27:17,860 INFO spawned: 'novnc' with pid 27
Traceback (most recent call last):
  File "/usr/local/lib/web/backend/run.py", line 9, in <module>
    from vnc.util import ignored
  File "/usr/local/lib/web/backend/vnc/util.py", line 5, in <module>
    from gevent import GreenletExit
ModuleNotFoundError: No module named 'gevent'
2022-02-23 01:27:17,887 INFO exited: web (exit status 1; not expected)
2022-02-23 01:27:18,870 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-02-23 01:27:18,871 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-02-23 01:27:18,871 INFO success: wm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-02-23 01:27:18,871 INFO success: lxpanel entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-02-23 01:27:18,871 INFO success: pcmanfm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-02-23 01:27:18,871 INFO success: x11vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-02-23 01:27:18,871 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-02-23 01:27:18,889 INFO spawned: 'web' with pid 79
Traceback (most recent call last):
  File "/usr/local/lib/web/backend/run.py", line 9, in <module>
    from vnc.util import ignored
  File "/usr/local/lib/web/backend/vnc/util.py", line 5, in <module>
    from gevent import GreenletExit
ModuleNotFoundError: No module named 'gevent'
2022-02-23 01:27:18,916 INFO exited: web (exit status 1; not expected)
2022-02-23 01:27:20,921 INFO spawned: 'web' with pid 80
Traceback (most recent call last):
  File "/usr/local/lib/web/backend/run.py", line 9, in <module>
    from vnc.util import ignored
  File "/usr/local/lib/web/backend/vnc/util.py", line 5, in <module>
    from gevent import GreenletExit
ModuleNotFoundError: No module named 'gevent'
2022-02-23 01:27:20,977 INFO exited: web (exit status 1; not expected)
2022-02-23 01:27:23,982 INFO spawned: 'web' with pid 81
Traceback (most recent call last):
  File "/usr/local/lib/web/backend/run.py", line 9, in <module>
    from vnc.util import ignored
  File "/usr/local/lib/web/backend/vnc/util.py", line 5, in <module>
    from gevent import GreenletExit
ModuleNotFoundError: No module named 'gevent'
2022-02-23 01:27:24,007 INFO exited: web (exit status 1; not expected)
2022-02-23 01:27:25,008 INFO gave up: web entered FATAL state, too many start retries too quickly
```

**Comment by seigot** [comment]
以下の単体だと動く

https://github.com/fcwu/docker-ubuntu-vnc-desktop#quick-start

```
$ docker run -p 6080:80 -v /dev/shm:/dev/shm dorowu/ubuntu-desktop-lxde-vnc:focal
```

**Comment by seigot** [comment]
python update (3.8-->3.9)の部分をアップデートしたら問題は起きなくなった。vncの部分で使っているpythonとの依存関係が存在するかも？

**Comment by seigot** [comment]
このissueが関係していそう
https://github.com/fcwu/docker-ubuntu-vnc-desktop/issues/202

**Comment by seigot** [comment]
どうもdocker-ubuntu-vnc-desktop固有の問題のようにみえる
目的はpython3.9以降にアップデートすることだが、 ubuntu22.04ではpython3.10がdefaultになるようなのでこのバージョンで無理に更新する必要はないように思う。

> Ubuntu 22.04 Features and Release Date
> https://linuxconfig.org/ubuntu-22-04-features-and-release-date
> Python 3.10.0 version will be shipped as a default with Ubuntu 22.04.
