### ISSUE TITLE
`load  None` `FileNotFoundError: [Errno 2] No such file or directory: 'None'`

### ISSUE THREAD

**Issue by seigot** [seigot/tetris#23]
学習モデルを読み込めない場合は`FileNotFoundError: [Errno 2] No such file or directory: 'None'`が出ると思う

```
$ python start.py -l2 -m predict
game_level: 2
game_time: 180
RANDOM_SEED: -1
IS_MODE :predict
OBSTACLE_HEIGHT: 0
OBSTACLE_PROBABILITY: 0
USER_NAME: window_sample
RESULT_LOG_JSON: result.json
Python 3.7.1
CompletedProcess(args='python --version', returncode=0, stderr='')
model name: DQNv2
set target network...
load  None
Traceback (most recent call last):
  File "game_manager/game_manager.py", line 247, in timerEvent
    self.nextMove = BLOCK_CONTROLLER_TRAIN.GetNextMove(nextMove, GameStatus,weight=self.weight)
  File "/Users/seigo/Desktop/python/tetris.endo/game_manager/machine_learning/block_controller_train.py", line 449, in GetNextMove
    self.set_parameter(weight=weight)
  File "/Users/seigo/Desktop/python/tetris.endo/game_manager/machine_learning/block_controller_train.py", line 99, in set_parameter
    self.model = torch.load(weight)
  File "/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'None'
error: subprocess failed.
(base) seigonoMacBook-puro-3868:tetris.endo seigo$ git remote -v
origin	https://github.com/EndoNrak/tetris (fetch)
origin	https://github.com/EndoNrak/tetris (push)
(base) seigonoMacBook-puro-3868:tetris.endo seigo$ git branch
```

**Comment by seigot** [comment]
学習モデルを読み込めているか確認する→解決
