### ISSUE TITLE
python3 start.py -m train_sample -d 1 -l 2 -t -1 実行時にエラー（RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! A）

### ISSUE THREAD

**Issue by seigot** [seigot/tetris#32]
```
(venvtest) ubuntu@ubuntu-ZBOX-EN72080V-EN72070V-EN52060V-EN51660T:~/tmp/tetris$ python3 start.py -m train_sample -d 1 -l 2 -t -1
game_level: 2
game_time: -1
RANDOM_SEED: -1
IS_MODE :train_sample
OBSTACLE_HEIGHT: 0
OBSTACLE_PROBABILITY: 0
USER_NAME: window_sample
RESULT_LOG_JSON: result.json
TRAIN_YAML: config/default.yaml
PREDICT_WEIGHT: outputs/latest/best_weight.pt
Python 3.9.9
CompletedProcess(args='python --version', returncode=0, stderr='')
model name: DQN
set target network...
================pass================
iter: 0 ,meory: 14/3000.0 , score: -1300, clear line: 0, block: 14 
================pass================
iter: 0 ,meory: 31/3000.0 , score: -1300, clear line: 0, block: 17 
================pass================
iter: 0 ,meory: 53/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 74/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 100/3000.0 , score: -1300, clear line: 0, block: 26 
================pass================
iter: 0 ,meory: 120/3000.0 , score: -1300, clear line: 0, block: 20 
================pass================
iter: 0 ,meory: 135/3000.0 , score: -1300, clear line: 0, block: 15 
================pass================
iter: 0 ,meory: 152/3000.0 , score: -1300, clear line: 0, block: 17 
================pass================
iter: 0 ,meory: 178/3000.0 , score: -1300, clear line: 0, block: 26 
================pass================
iter: 0 ,meory: 202/3000.0 , score: -1300, clear line: 0, block: 24 
================pass================
iter: 0 ,meory: 232/3000.0 , score: -1300, clear line: 0, block: 30 
================pass================
iter: 0 ,meory: 255/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 279/3000.0 , score: -1300, clear line: 0, block: 24 
================pass================
iter: 0 ,meory: 303/3000.0 , score: -1300, clear line: 0, block: 24 
================pass================
iter: 0 ,meory: 318/3000.0 , score: -1300, clear line: 0, block: 15 
================pass================
iter: 0 ,meory: 339/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 359/3000.0 , score: -1300, clear line: 0, block: 20 
================pass================
iter: 0 ,meory: 382/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 410/3000.0 , score: -1300, clear line: 0, block: 28 
================pass================
iter: 0 ,meory: 434/3000.0 , score: -1300, clear line: 0, block: 24 
================pass================
iter: 0 ,meory: 455/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 477/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 502/3000.0 , score: -1300, clear line: 0, block: 25 
================pass================
iter: 0 ,meory: 524/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 543/3000.0 , score: -1300, clear line: 0, block: 19 
================pass================
iter: 0 ,meory: 560/3000.0 , score: -1300, clear line: 0, block: 17 
================pass================
iter: 0 ,meory: 584/3000.0 , score: -1300, clear line: 0, block: 24 
================pass================
iter: 0 ,meory: 604/3000.0 , score: -1300, clear line: 0, block: 20 
================pass================
iter: 0 ,meory: 628/3000.0 , score: -1300, clear line: 0, block: 24 
================pass================
iter: 0 ,meory: 640/3000.0 , score: -1300, clear line: 0, block: 12 
================pass================
iter: 0 ,meory: 656/3000.0 , score: -1300, clear line: 0, block: 16 
================pass================
iter: 0 ,meory: 677/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 695/3000.0 , score: -1300, clear line: 0, block: 18 
================pass================
iter: 0 ,meory: 724/3000.0 , score: -1300, clear line: 0, block: 29 
================pass================
iter: 0 ,meory: 742/3000.0 , score: -1300, clear line: 0, block: 18 
================pass================
iter: 0 ,meory: 764/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 785/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 810/3000.0 , score: -1300, clear line: 0, block: 25 
================pass================
iter: 0 ,meory: 831/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 852/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 872/3000.0 , score: -1300, clear line: 0, block: 20 
================pass================
iter: 0 ,meory: 896/3000.0 , score: -1300, clear line: 0, block: 24 
================pass================
iter: 0 ,meory: 920/3000.0 , score: -1300, clear line: 0, block: 24 
================pass================
iter: 0 ,meory: 939/3000.0 , score: -1300, clear line: 0, block: 19 
================pass================
iter: 0 ,meory: 967/3000.0 , score: -1300, clear line: 0, block: 28 
================pass================
iter: 0 ,meory: 990/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 1013/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 1042/3000.0 , score: -1300, clear line: 0, block: 29 
================pass================
iter: 0 ,meory: 1070/3000.0 , score: -1300, clear line: 0, block: 28 
================pass================
iter: 0 ,meory: 1096/3000.0 , score: -1300, clear line: 0, block: 26 
================pass================
iter: 0 ,meory: 1127/3000.0 , score: -1300, clear line: 0, block: 31 
================pass================
iter: 0 ,meory: 1147/3000.0 , score: -1300, clear line: 0, block: 20 
================pass================
iter: 0 ,meory: 1171/3000.0 , score: -1300, clear line: 0, block: 24 
================pass================
iter: 0 ,meory: 1197/3000.0 , score: -1300, clear line: 0, block: 26 
================pass================
iter: 0 ,meory: 1212/3000.0 , score: -1300, clear line: 0, block: 15 
================pass================
iter: 0 ,meory: 1234/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 1252/3000.0 , score: -1300, clear line: 0, block: 18 
================pass================
iter: 0 ,meory: 1271/3000.0 , score: -1300, clear line: 0, block: 19 
================pass================
iter: 0 ,meory: 1300/3000.0 , score: -1300, clear line: 0, block: 29 
================pass================
iter: 0 ,meory: 1328/3000.0 , score: -1300, clear line: 0, block: 28 
================pass================
iter: 0 ,meory: 1351/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 1374/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 1398/3000.0 , score: -1300, clear line: 0, block: 24 
================pass================
iter: 0 ,meory: 1422/3000.0 , score: -1300, clear line: 0, block: 24 
================pass================
iter: 0 ,meory: 1446/3000.0 , score: -1300, clear line: 0, block: 24 
================pass================
iter: 0 ,meory: 1466/3000.0 , score: -1300, clear line: 0, block: 20 
================pass================
iter: 0 ,meory: 1480/3000.0 , score: -1300, clear line: 0, block: 14 
================pass================
iter: 0 ,meory: 1503/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 1521/3000.0 , score: -1300, clear line: 0, block: 18 
================pass================
iter: 0 ,meory: 1539/3000.0 , score: -1300, clear line: 0, block: 18 
================pass================
iter: 0 ,meory: 1562/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 1583/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 1607/3000.0 , score: -1300, clear line: 0, block: 24 
================pass================
iter: 0 ,meory: 1624/3000.0 , score: -1300, clear line: 0, block: 17 
================pass================
iter: 0 ,meory: 1650/3000.0 , score: -1300, clear line: 0, block: 26 
================pass================
iter: 0 ,meory: 1673/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 1688/3000.0 , score: -1300, clear line: 0, block: 15 
================pass================
iter: 0 ,meory: 1708/3000.0 , score: -1300, clear line: 0, block: 20 
================pass================
iter: 0 ,meory: 1729/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 1747/3000.0 , score: -1300, clear line: 0, block: 18 
================pass================
iter: 0 ,meory: 1770/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 1788/3000.0 , score: -1300, clear line: 0, block: 18 
================pass================
iter: 0 ,meory: 1815/3000.0 , score: -1300, clear line: 0, block: 27 
================pass================
iter: 0 ,meory: 1842/3000.0 , score: -1300, clear line: 0, block: 27 
================pass================
iter: 0 ,meory: 1867/3000.0 , score: -1300, clear line: 0, block: 25 
================pass================
iter: 0 ,meory: 1889/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 1908/3000.0 , score: -1300, clear line: 0, block: 19 
================pass================
iter: 0 ,meory: 1925/3000.0 , score: -1300, clear line: 0, block: 17 
================pass================
iter: 0 ,meory: 1948/3000.0 , score: -1200, clear line: 1, block: 23 
================pass================
iter: 0 ,meory: 1970/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 1991/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 2013/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 2039/3000.0 , score: -1300, clear line: 0, block: 26 
================pass================
iter: 0 ,meory: 2065/3000.0 , score: -1300, clear line: 0, block: 26 
================pass================
iter: 0 ,meory: 2088/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 2106/3000.0 , score: -1300, clear line: 0, block: 18 
================pass================
iter: 0 ,meory: 2130/3000.0 , score: -1200, clear line: 1, block: 24 
================pass================
iter: 0 ,meory: 2155/3000.0 , score: -1200, clear line: 1, block: 25 
================pass================
iter: 0 ,meory: 2172/3000.0 , score: -1300, clear line: 0, block: 17 
================pass================
iter: 0 ,meory: 2196/3000.0 , score: -1300, clear line: 0, block: 24 
================pass================
iter: 0 ,meory: 2221/3000.0 , score: -1300, clear line: 0, block: 25 
================pass================
iter: 0 ,meory: 2239/3000.0 , score: -1300, clear line: 0, block: 18 
================pass================
iter: 0 ,meory: 2264/3000.0 , score: -1300, clear line: 0, block: 25 
================pass================
iter: 0 ,meory: 2291/3000.0 , score: -1300, clear line: 0, block: 27 
================pass================
iter: 0 ,meory: 2322/3000.0 , score: -1300, clear line: 0, block: 31 
================pass================
iter: 0 ,meory: 2339/3000.0 , score: -1300, clear line: 0, block: 17 
================pass================
iter: 0 ,meory: 2368/3000.0 , score: -1300, clear line: 0, block: 29 
================pass================
iter: 0 ,meory: 2387/3000.0 , score: -1300, clear line: 0, block: 19 
================pass================
iter: 0 ,meory: 2406/3000.0 , score: -1300, clear line: 0, block: 19 
================pass================
iter: 0 ,meory: 2431/3000.0 , score: -1300, clear line: 0, block: 25 
================pass================
iter: 0 ,meory: 2450/3000.0 , score: -1300, clear line: 0, block: 19 
================pass================
iter: 0 ,meory: 2477/3000.0 , score: -1300, clear line: 0, block: 27 
================pass================
iter: 0 ,meory: 2500/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 2523/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 2548/3000.0 , score: -1300, clear line: 0, block: 25 
================pass================
iter: 0 ,meory: 2562/3000.0 , score: -1300, clear line: 0, block: 14 
================pass================
iter: 0 ,meory: 2582/3000.0 , score: -1300, clear line: 0, block: 20 
================pass================
iter: 0 ,meory: 2603/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 2626/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 2649/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 2675/3000.0 , score: -1300, clear line: 0, block: 26 
================pass================
iter: 0 ,meory: 2699/3000.0 , score: -1300, clear line: 0, block: 24 
================pass================
iter: 0 ,meory: 2718/3000.0 , score: -1300, clear line: 0, block: 19 
================pass================
iter: 0 ,meory: 2740/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 2762/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 2784/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 2809/3000.0 , score: -1300, clear line: 0, block: 25 
================pass================
iter: 0 ,meory: 2832/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 2853/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 2875/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 2894/3000.0 , score: -1300, clear line: 0, block: 19 
================pass================
iter: 0 ,meory: 2915/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 2944/3000.0 , score: -1300, clear line: 0, block: 29 
================pass================
iter: 0 ,meory: 2966/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 2984/3000.0 , score: -1300, clear line: 0, block: 18 
================update================
Traceback (most recent call last):
  File "/home/ubuntu/tmp/tetris/game_manager/game_manager.py", line 342, in timerEvent
    reset_callback_function()
  File "/home/ubuntu/tmp/tetris/game_manager/machine_learning/block_controller_train_sample.py", line 279, in update
    tuple(reward if done[0] else reward + self.gamma * prediction for done ,reward, prediction in
  File "/home/ubuntu/tmp/tetris/game_manager/machine_learning/block_controller_train_sample.py", line 279, in <genexpr>
    tuple(reward if done[0] else reward + self.gamma * prediction for done ,reward, prediction in
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
Aborted (core dumped)
error: subprocess failed.
(venvtest) ubuntu@ubuntu-ZBOX-EN72080V-EN72070V-EN52060V-EN51660T:~/tmp/tetris$ 
```

```
(venvtest) ubuntu@ubuntu-ZBOX-EN72080V-EN72070V-EN52060V-EN51660T:~/tmp/tetris$ python start.py -m train_sample2 -d 1 -l 2 -t -1
game_level: 2
game_time: -1
RANDOM_SEED: -1
IS_MODE :train_sample2
OBSTACLE_HEIGHT: 0
OBSTACLE_PROBABILITY: 0
USER_NAME: window_sample
RESULT_LOG_JSON: result.json
TRAIN_YAML: config/default.yaml
PREDICT_WEIGHT: outputs/latest/best_weight.pt
Python 3.9.9
CompletedProcess(args='python --version', returncode=0, stderr='')
model name: MLP
================pass================
iter: 0 ,meory: 12/3000.0 , score: -1300, clear line: 0, block: 12 
================pass================
iter: 0 ,meory: 34/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 58/3000.0 , score: -1300, clear line: 0, block: 24 
================pass================
iter: 0 ,meory: 76/3000.0 , score: -1300, clear line: 0, block: 18 
================pass================
iter: 0 ,meory: 97/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 118/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 136/3000.0 , score: -1300, clear line: 0, block: 18 
================pass================
iter: 0 ,meory: 169/3000.0 , score: -1200, clear line: 1, block: 33 
================pass================
iter: 0 ,meory: 188/3000.0 , score: -1300, clear line: 0, block: 19 
================pass================
iter: 0 ,meory: 209/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 239/3000.0 , score: -1300, clear line: 0, block: 30 
================pass================
iter: 0 ,meory: 262/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 281/3000.0 , score: -1300, clear line: 0, block: 19 
================pass================
iter: 0 ,meory: 301/3000.0 , score: -1300, clear line: 0, block: 20 
================pass================
iter: 0 ,meory: 322/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 350/3000.0 , score: -1300, clear line: 0, block: 28 
================pass================
iter: 0 ,meory: 371/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 396/3000.0 , score: -1300, clear line: 0, block: 25 
================pass================
iter: 0 ,meory: 416/3000.0 , score: -1300, clear line: 0, block: 20 
================pass================
iter: 0 ,meory: 433/3000.0 , score: -1300, clear line: 0, block: 17 
================pass================
iter: 0 ,meory: 452/3000.0 , score: -1300, clear line: 0, block: 19 
================pass================
iter: 0 ,meory: 479/3000.0 , score: -1300, clear line: 0, block: 27 
================pass================
iter: 0 ,meory: 509/3000.0 , score: -1200, clear line: 1, block: 30 
================pass================
iter: 0 ,meory: 531/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 553/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 577/3000.0 , score: -1300, clear line: 0, block: 24 
================pass================
iter: 0 ,meory: 602/3000.0 , score: -1300, clear line: 0, block: 25 
================pass================
iter: 0 ,meory: 627/3000.0 , score: -1300, clear line: 0, block: 25 
================pass================
iter: 0 ,meory: 645/3000.0 , score: -1300, clear line: 0, block: 18 
================pass================
iter: 0 ,meory: 664/3000.0 , score: -1300, clear line: 0, block: 19 
================pass================
iter: 0 ,meory: 685/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 707/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 730/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 749/3000.0 , score: -1300, clear line: 0, block: 19 
================pass================
iter: 0 ,meory: 777/3000.0 , score: -1300, clear line: 0, block: 28 
================pass================
iter: 0 ,meory: 799/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 820/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 838/3000.0 , score: -1300, clear line: 0, block: 18 
================pass================
iter: 0 ,meory: 861/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 881/3000.0 , score: -1300, clear line: 0, block: 20 
================pass================
iter: 0 ,meory: 907/3000.0 , score: -1300, clear line: 0, block: 26 
================pass================
iter: 0 ,meory: 926/3000.0 , score: -1300, clear line: 0, block: 19 
================pass================
iter: 0 ,meory: 945/3000.0 , score: -1300, clear line: 0, block: 19 
================pass================
iter: 0 ,meory: 962/3000.0 , score: -1300, clear line: 0, block: 17 
================pass================
iter: 0 ,meory: 980/3000.0 , score: -1300, clear line: 0, block: 18 
================pass================
iter: 0 ,meory: 1001/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 1022/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 1044/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 1072/3000.0 , score: -1300, clear line: 0, block: 28 
================pass================
iter: 0 ,meory: 1096/3000.0 , score: -1300, clear line: 0, block: 24 
================pass================
iter: 0 ,meory: 1117/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 1136/3000.0 , score: -1300, clear line: 0, block: 19 
================pass================
iter: 0 ,meory: 1159/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 1179/3000.0 , score: -1300, clear line: 0, block: 20 
================pass================
iter: 0 ,meory: 1194/3000.0 , score: -1300, clear line: 0, block: 15 
================pass================
iter: 0 ,meory: 1218/3000.0 , score: -1300, clear line: 0, block: 24 
================pass================
iter: 0 ,meory: 1240/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 1262/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 1290/3000.0 , score: -1300, clear line: 0, block: 28 
================pass================
iter: 0 ,meory: 1311/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 1327/3000.0 , score: -1300, clear line: 0, block: 16 
================pass================
iter: 0 ,meory: 1350/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 1366/3000.0 , score: -1300, clear line: 0, block: 16 
================pass================
iter: 0 ,meory: 1386/3000.0 , score: -1300, clear line: 0, block: 20 
================pass================
iter: 0 ,meory: 1405/3000.0 , score: -1300, clear line: 0, block: 19 
================pass================
iter: 0 ,meory: 1421/3000.0 , score: -1300, clear line: 0, block: 16 
================pass================
iter: 0 ,meory: 1450/3000.0 , score: -1300, clear line: 0, block: 29 
================pass================
iter: 0 ,meory: 1478/3000.0 , score: -1300, clear line: 0, block: 28 
================pass================
iter: 0 ,meory: 1497/3000.0 , score: -1300, clear line: 0, block: 19 
================pass================
iter: 0 ,meory: 1518/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 1536/3000.0 , score: -1300, clear line: 0, block: 18 
================pass================
iter: 0 ,meory: 1557/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 1578/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 1600/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 1623/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 1643/3000.0 , score: -1300, clear line: 0, block: 20 
================pass================
iter: 0 ,meory: 1660/3000.0 , score: -1300, clear line: 0, block: 17 
================pass================
iter: 0 ,meory: 1682/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 1704/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 1719/3000.0 , score: -1300, clear line: 0, block: 15 
================pass================
iter: 0 ,meory: 1742/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 1767/3000.0 , score: -1300, clear line: 0, block: 25 
================pass================
iter: 0 ,meory: 1783/3000.0 , score: -1300, clear line: 0, block: 16 
================pass================
iter: 0 ,meory: 1805/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 1824/3000.0 , score: -1300, clear line: 0, block: 19 
================pass================
iter: 0 ,meory: 1843/3000.0 , score: -1300, clear line: 0, block: 19 
================pass================
iter: 0 ,meory: 1867/3000.0 , score: -1300, clear line: 0, block: 24 
================pass================
iter: 0 ,meory: 1886/3000.0 , score: -1300, clear line: 0, block: 19 
================pass================
iter: 0 ,meory: 1902/3000.0 , score: -1300, clear line: 0, block: 16 
================pass================
iter: 0 ,meory: 1923/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 1945/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 1970/3000.0 , score: -1300, clear line: 0, block: 25 
================pass================
iter: 0 ,meory: 1993/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 2009/3000.0 , score: -1300, clear line: 0, block: 16 
================pass================
iter: 0 ,meory: 2029/3000.0 , score: -1300, clear line: 0, block: 20 
================pass================
iter: 0 ,meory: 2050/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 2071/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 2096/3000.0 , score: -1300, clear line: 0, block: 25 
================pass================
iter: 0 ,meory: 2117/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 2143/3000.0 , score: -1300, clear line: 0, block: 26 
================pass================
iter: 0 ,meory: 2167/3000.0 , score: -1300, clear line: 0, block: 24 
================pass================
iter: 0 ,meory: 2187/3000.0 , score: -1300, clear line: 0, block: 20 
================pass================
iter: 0 ,meory: 2211/3000.0 , score: -1300, clear line: 0, block: 24 
================pass================
iter: 0 ,meory: 2229/3000.0 , score: -1300, clear line: 0, block: 18 
================pass================
iter: 0 ,meory: 2247/3000.0 , score: -1300, clear line: 0, block: 18 
================pass================
iter: 0 ,meory: 2272/3000.0 , score: -1300, clear line: 0, block: 25 
================pass================
iter: 0 ,meory: 2298/3000.0 , score: -1300, clear line: 0, block: 26 
================pass================
iter: 0 ,meory: 2323/3000.0 , score: -1300, clear line: 0, block: 25 
================pass================
iter: 0 ,meory: 2340/3000.0 , score: -1300, clear line: 0, block: 17 
================pass================
iter: 0 ,meory: 2361/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 2384/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 2405/3000.0 , score: -1300, clear line: 0, block: 21 
================pass================
iter: 0 ,meory: 2434/3000.0 , score: -1300, clear line: 0, block: 29 
================pass================
iter: 0 ,meory: 2460/3000.0 , score: -1300, clear line: 0, block: 26 
================pass================
iter: 0 ,meory: 2476/3000.0 , score: -1300, clear line: 0, block: 16 
================pass================
iter: 0 ,meory: 2509/3000.0 , score: -1300, clear line: 0, block: 33 
================pass================
iter: 0 ,meory: 2528/3000.0 , score: -1300, clear line: 0, block: 19 
================pass================
iter: 0 ,meory: 2553/3000.0 , score: -1300, clear line: 0, block: 25 
================pass================
iter: 0 ,meory: 2576/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 2599/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 2624/3000.0 , score: -1300, clear line: 0, block: 25 
================pass================
iter: 0 ,meory: 2644/3000.0 , score: -1300, clear line: 0, block: 20 
================pass================
iter: 0 ,meory: 2666/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 2691/3000.0 , score: -1300, clear line: 0, block: 25 
================pass================
iter: 0 ,meory: 2711/3000.0 , score: -1300, clear line: 0, block: 20 
================pass================
iter: 0 ,meory: 2734/3000.0 , score: -1300, clear line: 0, block: 23 
================pass================
iter: 0 ,meory: 2754/3000.0 , score: -1300, clear line: 0, block: 20 
================pass================
iter: 0 ,meory: 2781/3000.0 , score: -1300, clear line: 0, block: 27 
================pass================
iter: 0 ,meory: 2809/3000.0 , score: -1300, clear line: 0, block: 28 
================pass================
iter: 0 ,meory: 2826/3000.0 , score: -1300, clear line: 0, block: 17 
================pass================
iter: 0 ,meory: 2848/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 2873/3000.0 , score: -1300, clear line: 0, block: 25 
================pass================
iter: 0 ,meory: 2895/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 2919/3000.0 , score: -1300, clear line: 0, block: 24 
================pass================
iter: 0 ,meory: 2944/3000.0 , score: -1300, clear line: 0, block: 25 
================pass================
iter: 0 ,meory: 2966/3000.0 , score: -1300, clear line: 0, block: 22 
================pass================
iter: 0 ,meory: 2989/3000.0 , score: -1300, clear line: 0, block: 23 
================update================
Traceback (most recent call last):
  File "/home/ubuntu/tmp/tetris/game_manager/game_manager.py", line 342, in timerEvent
    reset_callback_function()
  File "/home/ubuntu/tmp/tetris/game_manager/machine_learning/block_controller_train_sample2.py", line 280, in update
    tuple(reward if done[0] else reward + self.gamma * prediction for done ,reward, prediction in
  File "/home/ubuntu/tmp/tetris/game_manager/machine_learning/block_controller_train_sample2.py", line 280, in <genexpr>
    tuple(reward if done[0] else reward + self.gamma * prediction for done ,reward, prediction in
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
Aborted (core dumped)
error: subprocess failed.
(venvtest) ubuntu@ubuntu-ZBOX-EN72080V-EN72070V-EN52060V-EN51660T:~/tmp/tetris$ 

```

**Comment by seigot** [comment]
今後、ai.mdを補足するなら以下でしょうか？？  
https://github.com/seigot/tetris/blob/master/doc/files/ai.md  

学習のサンプルコード（block_controller_train_sample.py,block_controller_train_sample2.py,）
・学習時の各パラメータについて補足(start.py --train_sample xxx,,,)
・推論時の各パラメータについて補足(start.py --predict_sample)
・生成される学習モデルについての説明（何かあれば）
・サンプルの学習実行してからモデル作成までどれくらいおいておくか（何時間とか。ログを見る方法、epoch設定時の実行時間）
・サンプルの学習実行途中でキャンセルした場合のディレクトリの手動コピー（latestにコピー）
・サンプルの推論実行した時に成功したかどうかはどんな事を見ればいいのか
・中身の仕組みについて参考文献とかあれば添付とか？

学習を自プログラムで作る（block_controller_train.py）
・工夫のしどころの説明
　　（例）学習時のパラメータはどこを調整するか
・自プログラムでモデル作成する場合のやり方
（start.py --train, --predictのやり方とオプション。＋サンプルコードは修正しないでね！という案内）

提出について
・提出時のモデル登録について
　案
　・今はoutputs/を.gitignoreしてるので、submitディレクトリ等を作って登録してconfigを書き換える？？
　・weight置き場を集約する？？

**Comment by seigot** [comment]
提出時のイメージ
・predict.yamlを用意できないか（自動実行の関係で、--predict指定時に実行するファイルを固定で指定できるようにしたいと思い、、）
・最終的なweight置き場
・weightディレクトリの位置
　　sample_weight --> weightにかえる？
etc..

**Comment by seigot** [comment]
パラメータを工夫した上でpredict_sampleを使うのは良い気がする。
自動実行時はpredict,predict_sample,predict_sample2を対応する。weightはオプション指定する。
sample_weight --> weightにかえるだけする。
