### ISSUE TITLE
`python start.py`実行時に`TypeError: arguments did not match any overloaded call:`エラーが出る

### ISSUE THREAD

**Issue by seigot** [seigot/tetris#5]
`TypeError: arguments did not match any overloaded call:`エラーが出る

```
Desktop\work\tetris> python start.py
game_level: 1
game_time: 180
RANDOM_SEED: 0
IS_MODE :default
OBSTACLE_HEIGHT: 0
OBSTACLE_PROBABILITY: 0
USER_NAME: window_sample
RESULT_LOG_JSON: result.json
Python 3.10.0
CompletedProcess(args='python --version', returncode=0, stderr='')
Traceback (most recent call last):
  File "C:\Users\staka\Desktop\work\tetris\game_manager\game_manager.py", line 621, in paintEvent
    drawSquare(painter, x * self.gridSize + dx, y * self.gridSize + dy, val, self.gridSize)
  File "C:\Users\staka\Desktop\work\tetris\game_manager\game_manager.py", line 591, in drawSquare
    painter.fillRect(x + 1, y + 1, s - 2, s - 2, color)
TypeError: arguments did not match any overloaded call:
  fillRect(self, QRectF, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, QRect, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, int, int, int, int, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, QRectF, Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, QRect, Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, int, int, int, int, Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, int, int, int, int, Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, QRect, Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, QRectF, Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, int, int, int, int, Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, QRect, Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, QRectF, Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, int, int, int, int, QGradient.Preset): argument 1 has unexpected type 'float'
  fillRect(self, QRect, QGradient.Preset): argument 1 has unexpected type 'float'
  fillRect(self, QRectF, QGradient.Preset): argument 1 has unexpected type 'float'
error: subprocess failed.
```

**Comment by seigot** [comment]
https://github.com/seigot/tetris/commit/e345c7c70225756ead1f8f2fd49ea415b5132c25

**Comment by seigot** [comment]
解決済
