### ISSUE TITLE
強化学習要素の追加

### ISSUE THREAD

**Issue by seigot** [seigot/tetris#8]
強化学習要素の追加をしたい

**Comment by seigot** [comment]
[https://github.com/seigot/tetris/issues/4](https://github.com/seigot/tetris/issues/4)

**Comment by seigot** [comment]
> neteru-sanの強化学習は以下で動いた。
ただし移植が必要である。

```
    ## prediction
    git clone http://github.com/neteru141/tetris_game -b v1.1.0
    cd tetris_game
    bash start.sh -l2

    ## train
    git clone http://github.com/neteru141/tetris_game -b dev4
    cd tetris_game
    bash start.sh -l2
    ### その後、しばらく２０分くらい放置しておく
    ### train/tetris が学習モデル

    ## 以下のようにするとtrainしたモデルが動く
    git clone http://github.com/neteru141/tetris_game -b submit
    cd tetris_game
    bash start.sh -l2
```

> pip3 install -r requirements.txtする。requirements.txtの中身は以下の通り。

```
pyqt5
numpy
pillow
matplotlib
torch
torchvision 
torchaudio
tensorboardX

> パッチはこれをベースにするつもり
https://github.com/seigot/tools/tree/master/tetris/neteru141

**Comment by seigot** [comment]
参考サイト
https://github.com/uvipen/Tetris-deep-Q-learning-pytorch

**Comment by seigot** [comment]
推論時にネットワークモデル（deep_q_network.py）がどこにあるかでエラーが出る事がある
学習時と推論時に、deep_q_network.pyのパスに違いがあると生じる事がある。

```
$ python start.py -l2 -mpredict_sample -d100 -t18 --ShapeListMax 6
Traceback (most recent call last):
  File "game_manager/game_manager.py", line 237, in timerEvent
    self.nextMove = BLOCK_CONTROLLER_TRAIN_SAMPLE.GetNextMove(nextMove, GameStatus)
  File "/Users/seigo/Desktop/python/tetris/game_manager/machine_learning/block_controller_train_sample.py", line 334, in GetNextMove
    self.model = torch.load("{}/tetris".format(self.saved_path), map_location=lambda storage, loc: storage)
  File "/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'deep_q_network'
error: subprocess failed.
```

例えば以下のようにシンボリックリンクを付けてやると統一が図れるかもしれない

```
cd game_manager
ln -s machine_learning/deep_q_network.py deep_q_network.py
```

**Comment by seigot** [comment]
学習
```
$ python start.py -l2 -m train_sample -t -1 -d 1
```

推論
```
$ python start.py -l2 -mpredict_sample
or
$ python start.py -l2 -mpredict_sample -d1000 -t180 --ShapeListMax6
or
$ python start.py -l2 -m predict_sample -d100 -t18 --ShapeListMax6
```
